set_charge_window:
  target:
    entity:
      integration: jackery_home_cloud
      domain: sensor
  fields:
    slot:
      required: true
      example: 0
      selector:
        number:
          min: 0
          max: 9
          mode: box
    start:
      required: true
      example: "06:15:00"
      selector:
        time:
    end:
      required: true
      example: "07:15:00"
      selector:
        time:

set_discharge_window:
  target:
    entity:
      integration: jackery_home_cloud
      domain: sensor
  fields:
    slot:
      required: true
      example: 0
      selector:
        number:
          min: 0
          max: 9
          mode: box
    start:
      required: true
      example: "07:15:00"
      selector:
        time:
    end:
      required: true
      example: "08:15:00"
      selector:
        time:

clear_charge_window:
  target:
    entity:
      integration: jackery_home_cloud
      domain: sensor
  fields:
    slot:
      required: true
      example: 0
      selector:
        number:
          min: 0
          max: 9
          mode: box

clear_discharge_window:
  target:
    entity:
      integration: jackery_home_cloud
      domain: sensor
  fields:
    slot:
      required: true
      example: 0
      selector:
        number:
          min: 0
          max: 9
          mode: box
